<?php
/**
 * helpers/LangHelper.php
 * Gestion du multilinguisme FR / EN pour QueueCare (Cameroun)
 *
 * Utilisation :
 *   LangHelper::init();           // à appeler en début de page
 *   __('key')                     // retourne la traduction
 *   LangHelper::getLang()         // retourne 'fr' ou 'en'
 *   LangHelper::setLang('en')     // force la langue
 */

class LangHelper
{
    private static string $lang = 'fr';

    // ────────────────────────────────────────────────────────────────
    //  Initialisation
    // ────────────────────────────────────────────────────────────────

    public static function init(): void
    {
        // Priorité : session → default fr
        if (!empty($_SESSION['lang']) && in_array($_SESSION['lang'], ['fr', 'en'])) {
            self::$lang = $_SESSION['lang'];
        } else {
            self::$lang = 'fr';
        }
    }

    public static function setLang(string $lang): void
    {
        if (in_array($lang, ['fr', 'en'])) {
            self::$lang = $lang;
            $_SESSION['lang'] = $lang;
        }
    }

    public static function getLang(): string
    {
        return self::$lang;
    }

    /**
     * Retourne le dictionnaire complet de la langue courante, encodé en JSON,
     * pour être injecté côté JS (window.I18N) et permettre la traduction des
     * textes générés dynamiquement (template strings).
     */
    public static function toJson(): string
    {
        $translations = self::getTranslations();
        $dict = $translations[self::$lang] ?? $translations['fr'];
        return json_encode($dict, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_APOS);
    }

    // ────────────────────────────────────────────────────────────────
    //  Traduction
    // ────────────────────────────────────────────────────────────────

    public static function t(string $key): string
    {
        $translations = self::getTranslations();
        return $translations[self::$lang][$key]
            ?? $translations['fr'][$key]
            ?? $key;
    }

    // ────────────────────────────────────────────────────────────────
    //  Toutes les traductions
    // ────────────────────────────────────────────────────────────────

    private static function getTranslations(): array
    {
        return [
            // ════════════════════════════════════════════════════════
            //  FRANÇAIS
            // ════════════════════════════════════════════════════════
            'fr' => [
                // Commun
                'lang_label'        => 'Langue',
                'lang_fr'           => 'Français',
                'lang_en'           => 'Anglais',
                'lang_choose'       => 'Choisissez votre langue',
                'save'              => 'Enregistrer',
                'cancel'            => 'Annuler',
                'back'              => 'Retour',
                'loading'           => 'Chargement...',
                'success'           => 'Succès',
                'error'             => 'Erreur',
                'required'          => 'Requis',

                // Auth — commun
                'email'             => 'Email',
                'password'          => 'Mot de passe',
                'confirm_password'  => 'Confirmer le mot de passe',
                'new_password'      => 'Nouveau mot de passe',
                'current_password'  => 'Mot de passe actuel',
                'login'             => 'Se connecter',
                'logout'            => 'Se déconnecter',
                'register'          => 'S\'inscrire',
                'already_account'   => 'Déjà inscrit ?',
                'no_account'        => 'Pas encore inscrit ?',
                'forgot_password'   => 'Mot de passe oublié ?',
                'back_to_home'      => 'Retour à l\'accueil',

                // Champs profil
                'nom'               => 'Nom',
                'prenom'            => 'Prénom',
                'telephone'         => 'Téléphone',
                'specialite'        => 'Spécialité',
                'photo'             => 'Photo de profil',
                'choose_photo'      => 'Choisir une photo',

                // Profil — actions
                'my_profile'        => 'Mon profil',
                'edit_profile'      => 'Modifier le profil',
                'profile_updated'   => 'Profil mis à jour avec succès !',
                'profile_locked'    => 'Vérification requise',
                'profile_locked_sub'=> 'Entrez votre mot de passe pour accéder à votre profil.',
                'unlock'            => 'Accéder au profil',
                'wrong_password'    => 'Mot de passe incorrect.',
                'change_password'   => 'Changer le mot de passe',
                'password_hint'     => 'Min 8 car., 1 maj., 1 chiffre',
                'password_confirm_hint' => 'Répétez le mot de passe',
                'current_pw_required' => 'Requis pour changer le mot de passe',
                'save_changes'      => 'Enregistrer les modifications',

                // Langue dans profil
                'language_settings' => 'Langue de l\'interface',
                'language_changed'  => 'Langue modifiée avec succès.',

                // Inscription médecin
                'doctor_register_title' => 'Créer un compte',
                'doctor_register_sub'   => 'Rejoignez l\'équipe médicale',
                'doctor_space'          => 'Espace Médecin',
                'sous_service'          => 'Spécialité / Sous-service',
                'select_sous_service'   => 'Sélectionner votre sous-service',
                'consultations_per_hour'=> 'consultations/heure',
                'create_account'        => 'Créer mon compte',
                'pw_too_short'          => 'Minimum 8 caractères.',
                'pw_need_upper'         => 'Au moins une majuscule requise.',
                'pw_need_digit'         => 'Au moins un chiffre requis.',
                'pw_no_match'           => 'Les mots de passe ne correspondent pas.',
                'photo_formats'         => 'Formats acceptés: JPG, PNG (max 2MB)',
                'phone_hint'            => 'Chiffres et le signe + uniquement',
                'specialite_hint'       => 'Sélectionnez votre spécialité médicale',
                'terms_text'            => 'En vous inscrivant, vous acceptez les',
                'terms_link'            => 'conditions d\'utilisation',
                'privacy_link'          => 'politique de confidentialité',
                'and'                   => 'et la',

                // Inscription gestionnaire
                'manager_register_title'=> 'Créer un compte gestionnaire',
                'manager_space'         => 'Espace Gestionnaire',
                'full_name'             => 'Nom complet',

                // Inscription admin
                'admin_setup_title'     => 'Configuration initiale',
                'hospital_name'         => 'Nom de l\'hôpital',
                'admin_name'            => 'Nom de l\'administrateur',
                'setup_submit'          => 'Créer l\'hôpital et le compte',

                // Dashboard médecin
                'dashboard'             => 'Tableau de bord',
                'welcome'               => 'Bienvenue',
                'patients_waiting'      => 'Patients en attente',
                'consultation'          => 'Consultation',
                'next_patient'          => 'Patient suivant',
                'no_patient'            => 'Aucun patient en attente',
                'status_available'      => 'Disponible',
                'status_busy'           => 'En consultation',
                'status_break'          => 'En pause',

                // Navigation
                'nav_dashboard'         => 'Tableau de bord',
                'nav_profile'           => 'Profil',
                'nav_planning'          => 'Planning',
                'nav_stats'             => 'Statistiques',

                // ════════════════════════════════════════════════════════
                //  COMMUN AUX DASHBOARDS (médecin / gestionnaire / admin)
                // ════════════════════════════════════════════════════════
                'sidebar_home'              => 'Accueil',
                'sidebar_logout'            => 'Déconnexion',
                'lang_fr_full'              => 'Français',
                'lang_en_full'              => 'English',
                'refresh'                   => 'Actualiser',
                'refreshing'                => 'Mise à jour...',
                'menu'                      => 'Menu',
                'session_expiring'          => "Votre session expire dans moins d'1 minute.",
                'stay_connected'            => 'Rester connecté',
                'patient'                   => 'Patient',
                'phone'                     => 'Téléphone',
                'expected_time'             => 'Heure prévue',
                'start_time'                => 'Heure début',
                'end_time'                  => 'Heure fin',
                'status'                    => 'Statut',
                'action'                    => 'Action',
                'all'                       => 'Tous',
                'start'                     => 'Démarrer',
                'finish'                    => 'Terminer',
                'absent_btn'                => 'Absent',
                'pause_exam'                => 'Pause examen',
                'resume'                    => 'Reprendre',
                'resume_priority'           => '⭐ Reprendre (priorité)',
                'next_appointment'          => 'Prochain RDV',
                'postpone_tomorrow'         => 'Reporter au lendemain',
                'postpone_tomorrow_title'   => 'Reporter toutes les consultations du jour au lendemain en priorité',
                'urgency_btn'               => 'Urgence',
                'urgency_btn_title'         => "Je suis appelé en urgence : me rendre indisponible sans perdre ma file du jour",
                'urgency_confirm'           => "⚠️ Déclencher le mode urgence ?\n\nVous serez basculé en indisponible et déconnecté (immédiatement, ou dès la fin de la consultation en cours). Votre file du jour est conservée : vous redeviendrez disponible dès votre prochaine connexion.",
                'urgency_registered'        => "Urgence enregistrée. Vous serez déconnecté dès la fin de la consultation en cours.",
                'urgency_panel_title'       => 'Urgence — rendre un médecin indisponible',
                'urgency_no_doctor_available' => 'Aucun médecin disponible actuellement.',
                'urgency_btn_title_gestionnaire' => 'Signaler que ce médecin est appelé en urgence',
                'waiting_short'             => 'en attente',
                'status_treated'            => 'Traitée',
                'status_in_progress'        => 'En cours',
                'status_cancelled'          => 'Annulée',
                'status_absent'             => 'Absent',
                'status_waiting'            => 'En attente',
                'status_confirmed'          => 'Confirmé',
                'status_paused'             => 'En pause',
                'today_consultations'       => 'Consultations du jour',
                'no_consultation_today'     => "Aucune consultation programmée pour aujourd'hui.",
                'my_schedule'               => 'Mon planning',
                'my_timetable'              => 'Mon emploi du temps',
                'my_stats'                  => 'Mes statistiques',
                'history'                   => 'Historique',
                'consultation_count'        => 'consultation(s)',
                'prev_week'                 => 'Semaine préc.',
                'this_week'                 => 'Cette semaine',
                'next_week'                 => 'Semaine suiv.',
                'days_7'                    => '7 jours',
                'days_30'                   => '30 jours',
                'months_3'                  => '3 mois',
                'months_6'                  => '6 mois',
                'year_1'                    => '1 an',
                'since_beginning'           => 'Depuis le début',
                'from'                      => 'Du',
                'to'                        => 'Au',
                'reset_filters'             => 'Réinitialiser',
                'access_profile'            => 'Accéder au profil',
                'your_password'             => 'Votre mot de passe',
                'change_photo'              => 'Changer la photo',
                'formats_accepted_short'    => 'Formats: JPG, PNG (max 2MB)',
                'last_name'                 => 'Nom',
                'first_name'                => 'Prénom',
                'change_pw_title'           => 'Changer le mot de passe',
                'current_pw'                => 'Mot de passe actuel',
                'new_pw'                    => 'Nouveau mot de passe',
                'confirm'                   => 'Confirmer',
                'repeat'                    => 'Répéter',
                'save_btn'                  => 'Enregistrer',
                'pause_modal_title'         => 'Mettre en pause — Examen externe',
                'pause_reason'              => 'Motif de la pause',
                'pause_reason_ex'           => 'ex: Radio pulmonaire, Analyse sanguine…',
                'next_appt_modal_title'     => 'Fixer le prochain rendez-vous',
                'next_appt_reason_ex'       => 'ex: Contrôle post-opératoire, Résultats analyses…',
                'patient_returned_confirm'  => 'Le patient est revenu ? La consultation va reprendre.',
                'postpone_all_confirm'      => "⚠️ Reporter toutes vos consultations du jour au lendemain ?\n\nElles seront programmées demain en priorité, dans le même ordre.",
                'consultation_started'      => 'Consultation démarrée.',
                'consultation_finished'     => 'Consultation terminée.',
                'patient_marked_absent'     => 'Patient marqué absent.',
                'consultation_paused'       => 'Consultation mise en pause.',
                'consultation_resumed'      => 'Consultation reprise.',
                'rdv_planned'               => 'Rendez-vous planifié avec succès !',
                'rdv_failed'                => 'Impossible de créer le rendez-vous.',
                'network_error'             => 'Erreur réseau. Veuillez réessayer.',
                'network_error_short'       => 'Erreur réseau.',
                'unknown_error'             => 'Une erreur est survenue.',
                'choose_date'               => 'Veuillez choisir une date.',
                'postponed_to_tomorrow'     => 'Consultations reportées à demain.',
                'left_since'                => 'Parti depuis',
                'patient_stays_paused'      => "Le patient restera \"en pause\" jusqu'à ce que vous le repreniez ou le marquiez absent manuellement.",
                'consultation_mode'         => 'Vous consultez en tant que directeur-médecin. Toutes vos actions sont enregistrées normalement.',
                'total'                     => 'Total',
                'treated'                   => 'Traitées',
                'waiting'                   => 'En attente',
                'absents'                   => 'Absents',
                'cancelled_pl'              => 'Annulées',
                'no_result_for'             => 'Aucun résultat pour',
                'no_consultation_scheduled_today' => "Aucune consultation programmée pour aujourd'hui.",

                // ── Gestionnaire ──
                'queue'                     => "File d'attente",
                'all_consultations'         => 'Toutes les consultations',
                'register_patient'          => 'Enregistrer un patient',
                'qr_code'                   => 'QR Code',
                'doctors'                   => 'Médecins',
                'urgencies'                 => 'Urgences',
                'no_patient_waiting'        => 'Aucun patient en attente.',
                'rank'                      => 'Rang',
                'doctor'                    => 'Médecin',
                'wait_time'                 => "Temps d'attente",
                'call'                      => 'Appeler',
                'no_show'                   => 'Absent',
                'cancel_btn'                => 'Annuler',
                'patient_name'              => 'Nom du patient',
                'patient_first_name'        => 'Prénom du patient',
                'phone_number'              => 'Numéro de téléphone',
                'sub_service'               => 'Sous-service',
                'select'                    => 'Sélectionner',
                'register_btn'              => 'Enregistrer',
                'available'                 => 'Disponible',
                'busy'                      => 'Occupé',
                'on_break'                  => 'En pause',
                'generate_qr'               => 'Générer un QR Code',
                'download'                  => 'Télécharger',
                'print'                     => 'Imprimer',
                'new_urgency'               => 'Nouvelle urgence',
                'description'               => 'Description',
                'priority'                  => 'Priorité',
                'low'                       => 'Basse',
                'medium'                    => 'Moyenne',
                'high'                      => 'Haute',
                'close'                     => 'Fermer',
                'open'                      => 'Ouvert',
                'closed'                    => 'Fermé',

                // ── Admin ──
                'services'                  => 'Services',
                'managers'                  => 'Gestionnaires',
                'statistics'                => 'Statistiques',
                'settings'                  => 'Paramètres',
                'add'                       => 'Ajouter',
                'edit'                      => 'Modifier',
                'delete'                    => 'Supprimer',
                'name'                      => 'Nom',
                'actions'                   => 'Actions',
                'create'                    => 'Créer',
                'service_name'              => 'Nom du service',
                'manage'                    => 'Gérer',
                'active'                    => 'Actif',
                'inactive'                  => 'Inactif',
                'hospital'                  => 'Hôpital',
                'confirm_delete'            => 'Confirmer la suppression ?',
                'changes_saved'             => 'Modifications enregistrées.',
                'yes'                       => 'Oui',
                'no'                        => 'Non',
                'hours_label'               => 'Horaires',
                'break_label'               => 'Pause',
                'legend_scheduled'          => 'Programmée',
                'legend_in_progress'        => 'En cours',
                'legend_treated'            => 'Traité',
                'legend_paused'             => 'Pause',
                'legend_unavailable'        => 'Non disponible',
                'loading'                   => 'Chargement...',
                'period_label'              => 'Période :',
                'avg_duration'              => 'Durée moy.',
                'consultations_evolution'   => 'Évolution des consultations',
                'status_breakdown'          => 'Répartition par statut',
                'consultations_per_weekday' => 'Consultations par jour de semaine',
                'avg_wait_time_title'       => "Temps d'attente moyen des patients — Mon sous-service",
                'measured_consultations'    => 'Consultations mesurées',
                'chart_period'              => 'Période du graphique :',
                'avg_wait_global'           => 'Temps moyen global (depuis le début)',
                'avg_wait_7d'               => 'Temps moyen (7 derniers jours)',
                'avg_wait_30d'              => 'Temps moyen (30 derniers jours)',
                'consultation_history'      => 'Historique des consultations',
                'profile_lock_pw_input'     => 'Votre mot de passe',
                'pause_intro_text'          => 'Le patient va passer un examen rapide avant de revenir. Précisez le motif pour garder une trace.',
                'auto_priority'             => 'Priorité automatique',
                'auto_priority_text'        => '— à son retour, ce patient sera remis en tête de file.',
                'confirm_pause'             => 'Confirmer la pause',
                'rdv_date_label'            => 'Date du rendez-vous',
                'rdv_time_label'            => 'Heure du rendez-vous',
                'rdv_select_date_first'     => "Sélectionnez d'abord une date.",
                'rdv_reason_label'          => 'Motif / Notes (optionnel)',
                'confirm_rdv'               => 'Confirmer le RDV',
                'no_result_search'          => 'Aucun résultat pour cette recherche.',
                'no_consultation_scheduled' => 'Aucune consultation programmée.',
                'email_label'               => 'Email',
                'generic_error'             => 'Erreur',
                'cant_start'                => 'Impossible de démarrer',
                'cant_finish'               => 'Impossible de terminer',
                'consultation_paused_with'  => 'Consultation mise en pause —',
                'default_exam_reason'       => 'Examen externe',
                'consultation_resumed_ex'   => 'Consultation reprise !',
                'retry_please'              => 'Erreur réseau, veuillez réessayer.',
                'postponed_with_priority'   => 'Consultations reportées à demain avec priorité',
                'select_date_please'        => 'Veuillez sélectionner une date.',
                'select_slot_please'        => 'Veuillez sélectionner un créneau horaire.',
                'saving'                    => 'Enregistrement…',
                'rdv_confirmed'             => 'RDV confirmé',
                'slot_auto_blocked'         => 'Le créneau a été automatiquement bloqué dans le planning.',
                'close_btn'                 => 'Fermer',
                'spots_available'           => 'dispo',
                'priority_patients_banner'  => "Patient(s) revenu(s) d'examen — priorité absolue :",
                'call_asap'                 => 'À appeler dès que possible',
                'page_title_doctor'         => 'Tableau de bord Médecin — QueueCare',
                'no_consultation_found'     => 'Aucune consultation trouvée.',
                'date_label'                => 'Date',
                'start_short'               => 'Début',
                'duration_label'            => 'Durée',
                'mode_label'                => 'Mode',
                'manual_mode'               => 'Manuel',
                'loading_error'             => 'Erreur de chargement',
                'online_mode'               => 'En ligne',
                'onsite_mode'               => 'Sur place',
                'patient_colon'             => 'Patient :',
                'return_priority_badge'     => 'Priorité retour examen',
                'no_slot_available'         => "Aucun créneau disponible ce jour-là.",
                'wait_time_decreased'       => "Le temps d'attente a <strong>baissé de %s min</strong> en moyenne ces 7 derniers jours par rapport aux 30 derniers jours. Bonne performance !",
                'wait_time_increased'       => "Le temps d'attente a <strong>augmenté de %s min</strong> ces 7 derniers jours. Vigilance recommandée.",
                'wait_time_stable'          => "Le temps d'attente est <strong>stable</strong> (variation < 2 min entre les 7 et 30 derniers jours).",
                'measures_since'            => 'Mesures depuis le',
                'page_title_manager'        => 'Tableau de bord — QueueCare',
                'new_consultation'          => 'Nouvelle consultation',
                'patient_s'                 => 'patient(s)',
                'work_schedule'             => 'Emploi du temps',
                'no_consultations'          => 'Aucune consultation.',
                'total_consultations_day'   => 'Total consultations (jour)',
                'treated_consultations'     => 'Consultations traitées',
                'absent_patients'           => 'Patients absents',
                'cancelled_consultations'   => 'Consultations annulées',
                'online_bookings'           => 'Prises en ligne',
                'onsite_bookings'           => 'Prises sur place',
                'total_period'              => 'Total (période)',
                'treated_period'            => 'Traitées (période)',
                'absent_period'             => 'Absents (période)',
                'cancelled_period'          => 'Annulées (période)',
                'evolution_all_subservice'  => 'Évolution des consultations — Tout le sous-service',
                'no_doctor_assigned'        => 'Aucun médecin affecté à ce sous-service.',
                'doctor_activity_compare'   => 'Activité par médecin — Comparatif',
                'avg_wait_time_subservice'  => "Temps d'attente moyen des patients — Tout le sous-service",
                'doctor_colon'              => 'Médecin :',
                'all_doctors'               => '— Tous les médecins —',
                'legend_rest_closed'        => 'Repos/fermé',
                'today_btn'                 => "Aujourd'hui",
                'export_pdf'                => 'Exporter PDF',
                'print_btn'                 => 'Imprimer',
                'choose_mode_title'         => 'Choisir le mode',
                'manual_entry'              => 'Saisie manuelle',
                'fill_form'                 => 'Remplir le formulaire',
                'generate_qr_short'         => 'Générer un QR code',
                'register_consultation'     => 'Enregistrer une consultation',
                'phone_required'            => 'Téléphone *',
                'last_name_required'        => 'Nom *',
                'first_name_required'       => 'Prénom *',
                'initial_status'            => 'Statut initial',
                'motif_label'               => 'Motif',
                'regenerate'                => 'Régénérer',
                'left_for_exam'             => 'Parti(s) en examen :',
                'click_returned_alert'      => "Cliquez 🔔 Patient revenu dès qu'il/elle se présente à nouveau",
                'doctor_already_alerted_for'=> 'Médecin déjà averti pour :',
                'waiting_resume'            => '— en attente qu\'il reprenne la consultation',
                'doctor_alerted'            => 'Médecin averti',
                'no_consultation_found_full'=> 'Aucune consultation trouvée.',
                'session_expired'           => 'Session expirée.',
                'generation_error'          => 'Erreur lors de la génération.',
                'no_doctor_available'       => 'Aucun médecin disponible',
                'doctor_not_found'          => 'Médecin introuvable',
                'end_short'                 => 'Fin',
                'patient_back_confirm'      => "Le patient est revenu de son examen ? Le médecin va être averti pour qu'il reprenne la consultation.",
                'full_name'                 => 'Nom complet',
                'password_hint'             => 'Min 8 car., 1 maj., 1 chiffre',
                'report_total_footer'       => 'Total : %n consultation(s) — Généré le %d à %t',
                'msg_hopital_sauvegarde'    => "Configuration de l'hôpital sauvegardée.",
                'msg_utilisateur_cree'      => 'Utilisateur créé avec succès.',
                'msg_statut_mis_a_jour'     => 'Statut mis à jour.',
                'msg_ss_cree'               => 'Sous-service créé.',
                'msg_ss_modifie'            => 'Sous-service modifié.',
                'msg_ss_supprime'           => 'Sous-service supprimé.',
                'msg_ss_statut_maj'         => 'Statut du sous-service mis à jour.',
                'err_nom_hopital_requis'    => "Le nom de l'hôpital est requis.",
                'err_champs_vides'          => 'Tous les champs sont obligatoires.',
                'err_email_invalide'        => "L'adresse email est invalide.",
                'err_email_existe'          => 'Cette adresse email est déjà utilisée.',
                'err_role_invalide'         => 'Rôle invalide.',
                'err_creation_echouee'      => 'La création a échoué. Réessayez.',
                'err_sauvegarde_echouee'    => 'La sauvegarde a échoué.',
                'err_id_invalide'           => 'Identifiant invalide.',
                'err_ss_nom_requis'         => 'Le nom du sous-service est requis.',
                'err_ss_nom_existe'         => 'Ce nom de sous-service existe déjà.',
                'err_ss_donnees_invalides'  => 'Données du sous-service invalides.',
                'err_ss_echec'              => 'Opération échouée. Réessayez.',
                'err_ss_suppression_imp'    => 'Suppression impossible (dépendances existantes).',
                'my_hospital_default'       => 'Mon hôpital',
                'admin_title_prefix'        => 'Administration —',
                'navigation_label'          => 'Navigation',
                'hospital_config'           => 'Configuration hôpital',
                'account_label'             => 'Compte',
                'my_consultations_nav'      => 'Mes consultations',
                'setup_done_msg'            => "Installation terminée ! Configurez votre hôpital, puis créez vos équipes et départements.",
                'temp_password_title'       => 'Mot de passe temporaire — à communiquer une seule fois',
                'account_colon'             => 'Compte :',
                'hospital_config_title'     => "Configuration de l'hôpital",
                'hospital_name_label'       => "Nom de l'hôpital",
                'contact_email'             => 'Email de contact',
                'address_label'             => 'Adresse',
                'logo_label'                => 'Logo (JPG/PNG/SVG)',
                'general_hours_title'       => 'Horaires généraux des médecins',
                'general_hours_sync_note'   => '(synchronisés avec les dashboards médecin et gestionnaire)',
                'work_start_time'           => 'Heure de début de travail',
                'work_end_time'             => 'Heure de fin de travail',
                'break_start_optional'      => 'Début de pause (optionnel)',
                'break_end_optional'        => 'Fin de pause (optionnel)',
                'hours_info_note'           => "Ces horaires définissent la plage de travail par défaut affichée sur les plannings des médecins et du gestionnaire. Laissez les champs de pause vides si les médecins n'ont pas de pause déjeuner commune.",
                'new_sub_service'           => 'Nouveau sous-service',
                'sub_service_name_label'    => 'Nom',
                'default_duration'          => 'Durée par défaut',
                'hourly_capacity'           => 'Capacité horaire',
                'create_sub_service_btn'    => 'Créer le sous-service',
                'no_manager'                => 'Aucun gestionnaire enregistré.',
                'no_doctor'                 => 'Aucun médecin enregistré.',
                'no_sub_service'            => 'Aucun sous-service. Créez-en un ci-dessus.',
                'search_placeholder'        => 'Rechercher par désignation ou référence…',
                'filter_btn'                => 'Filtrer',
                'clear_btn'                 => 'Effacer',
                'created_at'                => 'Créé le',
                'disable_btn'               => 'Désactiver',
                'enable_btn'                => 'Activer',
                'edit_sub_service_title'    => 'Modifier le sous-service',
                'confirm_delete_title'      => 'Supprimer',
                'confirm_delete_text'       => 'Confirmer la suppression de',
                'confirm_delete_warning'    => 'Cette action est irréversible. Elle échoue s\'il existe des consultations ou médecins associés.',
                'delete_btn'                => 'Supprimer',
                'doctor_role_title'         => 'Activer votre rôle de médecin',
                'doctor_role_desc'          => 'En tant que directeur-médecin, vous pouvez traiter des consultations directement depuis ce tableau de bord. Remplissez ce formulaire une seule fois pour activer cette fonctionnalité.',
                'specialty_label'           => 'Spécialité médicale',
                'sub_service_consult_label' => 'Sous-service où vous consultez',
                'choose_sub_service'        => '— Choisir un sous-service —',
                'pro_phone_label'           => 'Téléphone professionnel',
                'activate_role_btn'         => 'Activer mon rôle de médecin',
                'activation_security_note'  => 'Cette activation est sécurisée. Vous pourrez toujours gérer vos consultations depuis cet onglet après activation.',
                'loading_consultations'     => 'Chargement de vos consultations…',
                'load_consult_error'        => 'Impossible de charger les consultations.',
                'enter_specialty_please'    => 'Veuillez saisir votre spécialité.',
                'choose_sub_service_please' => 'Veuillez choisir un sous-service.',
                'activation_in_progress'    => 'Activation en cours…',
                'activated_label'           => 'Activé !',
                'activation_error'          => "Erreur lors de l'activation.",
            ],
            // ════════════════════════════════════════════════════════
            //  ENGLISH
            // ════════════════════════════════════════════════════════
            'en' => [
                // Common
                'lang_label'        => 'Language',
                'lang_fr'           => 'French',
                'lang_en'           => 'English',
                'lang_choose'       => 'Choose your language',
                'save'              => 'Save',
                'cancel'            => 'Cancel',
                'back'              => 'Back',
                'loading'           => 'Loading...',
                'success'           => 'Success',
                'error'             => 'Error',
                'required'          => 'Required',

                // Auth — common
                'email'             => 'Email',
                'password'          => 'Password',
                'confirm_password'  => 'Confirm password',
                'new_password'      => 'New password',
                'current_password'  => 'Current password',
                'login'             => 'Log in',
                'logout'            => 'Log out',
                'register'          => 'Sign up',
                'already_account'   => 'Already registered?',
                'no_account'        => 'Not yet registered?',
                'forgot_password'   => 'Forgot password?',
                'back_to_home'      => 'Back to home',

                // Profile fields
                'nom'               => 'Last name',
                'prenom'            => 'First name',
                'telephone'         => 'Phone',
                'specialite'        => 'Specialty',
                'photo'             => 'Profile photo',
                'choose_photo'      => 'Choose a photo',

                // Profile — actions
                'my_profile'        => 'My profile',
                'edit_profile'      => 'Edit profile',
                'profile_updated'   => 'Profile updated successfully!',
                'profile_locked'    => 'Verification required',
                'profile_locked_sub'=> 'Enter your password to access your profile.',
                'unlock'            => 'Access profile',
                'wrong_password'    => 'Incorrect password.',
                'change_password'   => 'Change password',
                'password_hint'     => 'Min 8 chars., 1 uppercase, 1 digit',
                'password_confirm_hint' => 'Repeat password',
                'current_pw_required' => 'Required to change password',
                'save_changes'      => 'Save changes',

                // Language in profile
                'language_settings' => 'Interface language',
                'language_changed'  => 'Language changed successfully.',

                // Doctor registration
                'doctor_register_title' => 'Create an account',
                'doctor_register_sub'   => 'Join the medical team',
                'doctor_space'          => 'Doctor Portal',
                'sous_service'          => 'Specialty / Sub-service',
                'select_sous_service'   => 'Select your sub-service',
                'consultations_per_hour'=> 'consultations/hour',
                'create_account'        => 'Create my account',
                'pw_too_short'          => 'Minimum 8 characters.',
                'pw_need_upper'         => 'At least one uppercase letter required.',
                'pw_need_digit'         => 'At least one digit required.',
                'pw_no_match'           => 'Passwords do not match.',
                'photo_formats'         => 'Accepted formats: JPG, PNG (max 2MB)',
                'phone_hint'            => 'Digits and + sign only',
                'specialite_hint'       => 'Select your medical specialty',
                'terms_text'            => 'By signing up, you agree to the',
                'terms_link'            => 'terms of use',
                'privacy_link'          => 'privacy policy',
                'and'                   => 'and the',

                // Manager registration
                'manager_register_title'=> 'Create a manager account',
                'manager_space'         => 'Manager Portal',
                'full_name'             => 'Full name',

                // Admin registration
                'admin_setup_title'     => 'Initial setup',
                'hospital_name'         => 'Hospital name',
                'admin_name'            => 'Administrator name',
                'setup_submit'          => 'Create hospital and account',

                // Doctor dashboard
                'dashboard'             => 'Dashboard',
                'welcome'               => 'Welcome',
                'patients_waiting'      => 'Waiting patients',
                'consultation'          => 'Consultation',
                'next_patient'          => 'Next patient',
                'no_patient'            => 'No patients waiting',
                'status_available'      => 'Available',
                'status_busy'           => 'In consultation',
                'status_break'          => 'On break',

                // Navigation
                'nav_dashboard'         => 'Dashboard',
                'nav_profile'           => 'Profile',
                'nav_planning'          => 'Schedule',
                'nav_stats'             => 'Statistics',

                // ════════════════════════════════════════════════════════
                //  COMMON TO DASHBOARDS (doctor / manager / admin)
                // ════════════════════════════════════════════════════════
                'sidebar_home'              => 'Home',
                'sidebar_logout'            => 'Log out',
                'lang_fr_full'              => 'French',
                'lang_en_full'              => 'English',
                'refresh'                   => 'Refresh',
                'refreshing'                => 'Updating...',
                'menu'                      => 'Menu',
                'session_expiring'          => 'Your session expires in less than 1 minute.',
                'stay_connected'            => 'Stay connected',
                'patient'                   => 'Patient',
                'phone'                     => 'Phone',
                'expected_time'             => 'Expected time',
                'start_time'                => 'Start time',
                'end_time'                  => 'End time',
                'status'                    => 'Status',
                'action'                    => 'Action',
                'all'                       => 'All',
                'start'                     => 'Start',
                'finish'                    => 'Finish',
                'absent_btn'                => 'Absent',
                'pause_exam'                => 'Pause for exam',
                'resume'                    => 'Resume',
                'resume_priority'           => '⭐ Resume (priority)',
                'next_appointment'          => 'Next appointment',
                'postpone_tomorrow'         => 'Postpone to tomorrow',
                'postpone_tomorrow_title'   => "Postpone all of today's consultations to tomorrow with priority",
                'urgency_btn'               => 'Emergency',
                'urgency_btn_title'         => "I'm called away urgently: go unavailable without losing today's queue",
                'urgency_confirm'           => "⚠️ Trigger emergency mode?\n\nYou will be marked unavailable and logged out (right away, or as soon as the current consultation ends). Today's queue is kept: you'll become available again as soon as you log back in.",
                'urgency_registered'        => "Emergency registered. You'll be logged out as soon as the current consultation ends.",
                'urgency_panel_title'       => 'Emergency — mark a doctor unavailable',
                'urgency_no_doctor_available' => 'No doctor currently available.',
                'urgency_btn_title_gestionnaire' => 'Report that this doctor has been called away urgently',
                'waiting_short'             => 'waiting',
                'status_treated'            => 'Treated',
                'status_in_progress'        => 'In progress',
                'status_cancelled'          => 'Cancelled',
                'status_absent'             => 'Absent',
                'status_waiting'            => 'Waiting',
                'status_confirmed'          => 'Confirmed',
                'status_paused'             => 'Paused',
                'today_consultations'       => "Today's consultations",
                'no_consultation_today'     => 'No consultation scheduled for today.',
                'my_schedule'               => 'My schedule',
                'my_timetable'              => 'My timetable',
                'my_stats'                  => 'My statistics',
                'history'                   => 'History',
                'consultation_count'        => 'consultation(s)',
                'prev_week'                 => 'Previous week',
                'this_week'                 => 'This week',
                'next_week'                 => 'Next week',
                'days_7'                    => '7 days',
                'days_30'                   => '30 days',
                'months_3'                  => '3 months',
                'months_6'                  => '6 months',
                'year_1'                    => '1 year',
                'since_beginning'           => 'Since the beginning',
                'from'                      => 'From',
                'to'                        => 'To',
                'reset_filters'             => 'Reset',
                'access_profile'            => 'Access profile',
                'your_password'             => 'Your password',
                'change_photo'              => 'Change photo',
                'formats_accepted_short'    => 'Formats: JPG, PNG (max 2MB)',
                'last_name'                 => 'Last name',
                'first_name'                => 'First name',
                'change_pw_title'           => 'Change password',
                'current_pw'                => 'Current password',
                'new_pw'                    => 'New password',
                'confirm'                   => 'Confirm',
                'repeat'                    => 'Repeat',
                'save_btn'                  => 'Save',
                'pause_modal_title'         => 'Pause — External exam',
                'pause_reason'              => 'Reason for pause',
                'pause_reason_ex'           => 'e.g.: Chest X-ray, Blood test…',
                'next_appt_modal_title'     => 'Set the next appointment',
                'next_appt_reason_ex'       => 'e.g.: Post-op check-up, Lab results…',
                'patient_returned_confirm'  => 'Has the patient returned? The consultation will resume.',
                'postpone_all_confirm'      => "⚠️ Postpone all of today's consultations to tomorrow?\n\nThey will be scheduled tomorrow with priority, in the same order.",
                'consultation_started'      => 'Consultation started.',
                'consultation_finished'     => 'Consultation finished.',
                'patient_marked_absent'     => 'Patient marked absent.',
                'consultation_paused'       => 'Consultation paused.',
                'consultation_resumed'      => 'Consultation resumed.',
                'rdv_planned'               => 'Appointment scheduled successfully!',
                'rdv_failed'                => 'Unable to create the appointment.',
                'network_error'             => 'Network error. Please try again.',
                'network_error_short'       => 'Network error.',
                'unknown_error'             => 'An error occurred.',
                'choose_date'               => 'Please choose a date.',
                'postponed_to_tomorrow'     => 'Consultations postponed to tomorrow.',
                'left_since'                => 'Left',
                'patient_stays_paused'      => 'The patient will remain "paused" until you resume them or mark them absent manually.',
                'consultation_mode'         => 'You are consulting as a director-physician. All your actions are recorded normally.',
                'total'                     => 'Total',
                'treated'                   => 'Treated',
                'waiting'                   => 'Waiting',
                'absents'                   => 'Absent',
                'cancelled_pl'              => 'Cancelled',
                'no_result_for'             => 'No results for',
                'no_consultation_scheduled_today' => 'No consultation scheduled for today.',

                // ── Manager ──
                'queue'                     => 'Queue',
                'all_consultations'         => 'All consultations',
                'register_patient'          => 'Register a patient',
                'qr_code'                   => 'QR Code',
                'doctors'                   => 'Doctors',
                'urgencies'                 => 'Urgent cases',
                'no_patient_waiting'        => 'No patient waiting.',
                'rank'                      => 'Rank',
                'doctor'                    => 'Doctor',
                'wait_time'                 => 'Wait time',
                'call'                      => 'Call',
                'no_show'                   => 'No-show',
                'cancel_btn'                => 'Cancel',
                'patient_name'              => 'Patient last name',
                'patient_first_name'        => 'Patient first name',
                'phone_number'              => 'Phone number',
                'sub_service'               => 'Sub-service',
                'select'                    => 'Select',
                'register_btn'              => 'Register',
                'available'                 => 'Available',
                'busy'                      => 'Busy',
                'on_break'                  => 'On break',
                'generate_qr'               => 'Generate a QR Code',
                'download'                  => 'Download',
                'print'                     => 'Print',
                'new_urgency'               => 'New urgent case',
                'description'               => 'Description',
                'priority'                  => 'Priority',
                'low'                       => 'Low',
                'medium'                    => 'Medium',
                'high'                      => 'High',
                'close'                     => 'Close',
                'open'                      => 'Open',
                'closed'                    => 'Closed',

                // ── Admin ──
                'services'                  => 'Services',
                'managers'                  => 'Managers',
                'statistics'                => 'Statistics',
                'settings'                  => 'Settings',
                'add'                       => 'Add',
                'edit'                      => 'Edit',
                'delete'                    => 'Delete',
                'name'                      => 'Name',
                'actions'                   => 'Actions',
                'create'                    => 'Create',
                'service_name'              => 'Service name',
                'manage'                    => 'Manage',
                'active'                    => 'Active',
                'inactive'                  => 'Inactive',
                'hospital'                  => 'Hospital',
                'confirm_delete'            => 'Confirm deletion?',
                'changes_saved'             => 'Changes saved.',
                'yes'                       => 'Yes',
                'no'                        => 'No',
                'hours_label'               => 'Hours',
                'break_label'               => 'Break',
                'legend_scheduled'          => 'Scheduled',
                'legend_in_progress'        => 'In progress',
                'legend_treated'            => 'Treated',
                'legend_paused'             => 'Paused',
                'legend_unavailable'        => 'Unavailable',
                'loading'                   => 'Loading...',
                'period_label'              => 'Period:',
                'avg_duration'              => 'Avg. duration',
                'consultations_evolution'   => 'Consultation trends',
                'status_breakdown'          => 'Breakdown by status',
                'consultations_per_weekday' => 'Consultations per weekday',
                'avg_wait_time_title'       => 'Average patient wait time — My sub-service',
                'measured_consultations'    => 'Measured consultations',
                'chart_period'              => 'Chart period:',
                'avg_wait_global'           => 'Overall average time (since the beginning)',
                'avg_wait_7d'               => 'Average time (last 7 days)',
                'avg_wait_30d'              => 'Average time (last 30 days)',
                'consultation_history'      => 'Consultation history',
                'profile_lock_pw_input'     => 'Your password',
                'pause_intro_text'          => 'The patient will undergo a quick exam before returning. Please specify the reason to keep a record.',
                'auto_priority'             => 'Automatic priority',
                'auto_priority_text'        => '— upon return, this patient will be moved back to the front of the queue.',
                'confirm_pause'             => 'Confirm pause',
                'rdv_date_label'            => 'Appointment date',
                'rdv_time_label'            => 'Appointment time',
                'rdv_select_date_first'     => 'Select a date first.',
                'rdv_reason_label'          => 'Reason / Notes (optional)',
                'confirm_rdv'               => 'Confirm appointment',
                'no_result_search'          => 'No results for this search.',
                'no_consultation_scheduled' => 'No consultation scheduled.',
                'email_label'               => 'Email',
                'generic_error'             => 'Error',
                'cant_start'                => 'Unable to start',
                'cant_finish'               => 'Unable to finish',
                'consultation_paused_with'  => 'Consultation paused —',
                'default_exam_reason'       => 'External exam',
                'consultation_resumed_ex'   => 'Consultation resumed!',
                'retry_please'              => 'Network error, please try again.',
                'postponed_with_priority'   => 'Consultations postponed to tomorrow with priority',
                'select_date_please'        => 'Please select a date.',
                'select_slot_please'        => 'Please select a time slot.',
                'saving'                    => 'Saving…',
                'rdv_confirmed'             => 'Appointment confirmed',
                'slot_auto_blocked'         => 'The time slot has been automatically blocked in the schedule.',
                'close_btn'                 => 'Close',
                'spots_available'           => 'available',
                'priority_patients_banner'  => 'Patient(s) back from exam — absolute priority:',
                'call_asap'                 => 'Call as soon as possible',
                'page_title_doctor'         => 'Doctor Dashboard — QueueCare',
                'no_consultation_found'     => 'No consultation found.',
                'date_label'                => 'Date',
                'start_short'               => 'Start',
                'duration_label'            => 'Duration',
                'mode_label'                => 'Mode',
                'manual_mode'               => 'Manual',
                'loading_error'             => 'Loading error',
                'online_mode'               => 'Online',
                'onsite_mode'               => 'On-site',
                'patient_colon'             => 'Patient:',
                'return_priority_badge'     => 'Priority on return from exam',
                'no_slot_available'         => 'No time slot available that day.',
                'wait_time_decreased'       => 'The wait time has <strong>decreased by %s min</strong> on average over the last 7 days compared to the last 30 days. Good performance!',
                'wait_time_increased'       => 'The wait time has <strong>increased by %s min</strong> over the last 7 days. Attention recommended.',
                'wait_time_stable'          => 'The wait time is <strong>stable</strong> (variation < 2 min between the last 7 and 30 days).',
                'measures_since'            => 'Measures since',
                'page_title_manager'        => 'Dashboard — QueueCare',
                'new_consultation'          => 'New consultation',
                'patient_s'                 => 'patient(s)',
                'work_schedule'             => 'Work schedule',
                'no_consultations'          => 'No consultations.',
                'total_consultations_day'   => 'Total consultations (day)',
                'treated_consultations'     => 'Treated consultations',
                'absent_patients'           => 'Absent patients',
                'cancelled_consultations'   => 'Cancelled consultations',
                'online_bookings'           => 'Online bookings',
                'onsite_bookings'           => 'On-site bookings',
                'total_period'              => 'Total (period)',
                'treated_period'            => 'Treated (period)',
                'absent_period'             => 'Absent (period)',
                'cancelled_period'          => 'Cancelled (period)',
                'evolution_all_subservice'  => 'Consultation trends — Entire sub-service',
                'no_doctor_assigned'        => 'No doctor assigned to this sub-service.',
                'doctor_activity_compare'   => 'Activity by doctor — Comparison',
                'avg_wait_time_subservice'  => 'Average patient wait time — Entire sub-service',
                'doctor_colon'              => 'Doctor:',
                'all_doctors'               => '— All doctors —',
                'legend_rest_closed'        => 'Off/closed',
                'today_btn'                 => 'Today',
                'export_pdf'                => 'Export PDF',
                'print_btn'                 => 'Print',
                'choose_mode_title'         => 'Choose mode',
                'manual_entry'              => 'Manual entry',
                'fill_form'                 => 'Fill the form',
                'generate_qr_short'         => 'Generate a QR code',
                'register_consultation'     => 'Register a consultation',
                'phone_required'            => 'Phone *',
                'last_name_required'        => 'Last name *',
                'first_name_required'       => 'First name *',
                'initial_status'            => 'Initial status',
                'motif_label'               => 'Reason',
                'regenerate'                => 'Regenerate',
                'left_for_exam'             => 'Gone for exam:',
                'click_returned_alert'      => 'Click 🔔 Patient returned as soon as they show up again',
                'doctor_already_alerted_for'=> 'Doctor already alerted for:',
                'waiting_resume'            => '— waiting for them to resume the consultation',
                'doctor_alerted'            => 'Doctor alerted',
                'no_consultation_found_full'=> 'No consultation found.',
                'session_expired'           => 'Session expired.',
                'generation_error'          => 'Error during generation.',
                'no_doctor_available'       => 'No doctor available',
                'doctor_not_found'          => 'Doctor not found',
                'end_short'                 => 'End',
                'patient_back_confirm'      => 'Has the patient returned from their exam? The doctor will be notified to resume the consultation.',
                'full_name'                 => 'Full name',
                'password_hint'             => 'Min 8 chars, 1 uppercase, 1 digit',
                'report_total_footer'       => 'Total: %n consultation(s) — Generated on %d at %t',
                'msg_hopital_sauvegarde'    => 'Hospital configuration saved.',
                'msg_utilisateur_cree'      => 'User created successfully.',
                'msg_statut_mis_a_jour'     => 'Status updated.',
                'msg_ss_cree'               => 'Sub-service created.',
                'msg_ss_modifie'            => 'Sub-service edited.',
                'msg_ss_supprime'           => 'Sub-service deleted.',
                'msg_ss_statut_maj'         => 'Sub-service status updated.',
                'err_nom_hopital_requis'    => 'Hospital name is required.',
                'err_champs_vides'          => 'All fields are required.',
                'err_email_invalide'        => 'Invalid email address.',
                'err_email_existe'          => 'This email address is already in use.',
                'err_role_invalide'         => 'Invalid role.',
                'err_creation_echouee'      => 'Creation failed. Please try again.',
                'err_sauvegarde_echouee'    => 'Save failed.',
                'err_id_invalide'           => 'Invalid ID.',
                'err_ss_nom_requis'         => 'Sub-service name is required.',
                'err_ss_nom_existe'         => 'This sub-service name already exists.',
                'err_ss_donnees_invalides'  => 'Invalid sub-service data.',
                'err_ss_echec'              => 'Operation failed. Please try again.',
                'err_ss_suppression_imp'    => 'Cannot delete (existing dependencies).',
                'my_hospital_default'       => 'My hospital',
                'admin_title_prefix'        => 'Administration —',
                'navigation_label'          => 'Navigation',
                'hospital_config'           => 'Hospital configuration',
                'account_label'             => 'Account',
                'my_consultations_nav'      => 'My consultations',
                'setup_done_msg'            => 'Setup complete! Configure your hospital, then create your teams and departments.',
                'temp_password_title'       => 'Temporary password — share once only',
                'account_colon'             => 'Account:',
                'hospital_config_title'     => 'Hospital configuration',
                'hospital_name_label'       => 'Hospital name',
                'contact_email'             => 'Contact email',
                'address_label'             => 'Address',
                'logo_label'                => 'Logo (JPG/PNG/SVG)',
                'general_hours_title'       => 'General doctor hours',
                'general_hours_sync_note'   => '(synced with doctor and manager dashboards)',
                'work_start_time'           => 'Work start time',
                'work_end_time'             => 'Work end time',
                'break_start_optional'      => 'Break start (optional)',
                'break_end_optional'        => 'Break end (optional)',
                'hours_info_note'           => "These hours define the default working range shown on doctor and manager schedules. Leave break fields empty if doctors don't share a lunch break.",
                'new_sub_service'           => 'New sub-service',
                'sub_service_name_label'    => 'Name',
                'default_duration'          => 'Default duration',
                'hourly_capacity'           => 'Hourly capacity',
                'create_sub_service_btn'    => 'Create sub-service',
                'no_manager'                => 'No manager registered.',
                'no_doctor'                 => 'No doctor registered.',
                'no_sub_service'            => 'No sub-service. Create one above.',
                'search_placeholder'        => 'Search by name or reference…',
                'filter_btn'                => 'Filter',
                'clear_btn'                 => 'Clear',
                'created_at'                => 'Created on',
                'disable_btn'               => 'Disable',
                'enable_btn'                => 'Enable',
                'edit_sub_service_title'    => 'Edit sub-service',
                'confirm_delete_title'      => 'Delete',
                'confirm_delete_text'       => 'Confirm deletion of',
                'confirm_delete_warning'    => 'This action is irreversible. It will fail if consultations or doctors are associated.',
                'delete_btn'                => 'Delete',
                'doctor_role_title'         => 'Activate your doctor role',
                'doctor_role_desc'          => 'As a director-physician, you can handle consultations directly from this dashboard. Fill in this form once to enable this feature.',
                'specialty_label'           => 'Medical specialty',
                'sub_service_consult_label' => 'Sub-service where you consult',
                'choose_sub_service'        => '— Choose a sub-service —',
                'pro_phone_label'           => 'Professional phone',
                'activate_role_btn'         => 'Activate my doctor role',
                'activation_security_note'  => 'This activation is secure. You can always manage your consultations from this tab after activation.',
                'loading_consultations'     => 'Loading your consultations…',
                'load_consult_error'        => 'Unable to load consultations.',
                'enter_specialty_please'    => 'Please enter your specialty.',
                'choose_sub_service_please' => 'Please choose a sub-service.',
                'activation_in_progress'    => 'Activating…',
                'activated_label'           => 'Activated!',
                'activation_error'          => 'Activation error.',
            ],
        ];
    }
}

// Fonction globale raccourcie
if (!function_exists('__')) {
    function __(string $key): string {
        return LangHelper::t($key);
    }
}